### ISSUE TITLE
github.hua0512.download.exceptions.DownloadErrorException: ffmpeg download failed

### ISSUE THREAD

**Issue by blueslmj** [stream-rec/stream-rec#196]
github.hua0512.download.exceptions.DownloadErrorException: ffmpeg download failed
	at github.hua0512.plugins.download.engines.FFmpegDownloadEngine.handleExitCodeAndStreamer(FFmpegDownloadEngine.kt:230)
	at github.hua0512.plugins.download.engines.FFmpegDownloadEngine$start$2.invokeSuspend(FFmpegDownloadEngine.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:266)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)

我自己下载了ffmpeg 怎么设置路径呢？

**Comment by hua0512** [comment]
添加到系统内的PATH环境变量或者使用`FFMPEG_PATH`环境变量
