### ISSUE TITLE
androidx.sqlite.SQLiteException: Error code: 5, message: Timed out attempting to acquire a writer connection

### ISSUE THREAD

**Issue by hua0512** [stream-rec/stream-rec#222]
[Google IssueTracker](https://issuetracker.google.com/issues/347737870)

11-04 00:14:21.038 [DefaultDispatcher-worker-30] ERROR g.hua0512.services.DownloadService - Failed to save stream data
androidx.sqlite.SQLiteException: Error code: 5, message: Timed out attempting to acquire a writer connection.

Writer pool:
	androidx.room.coroutines.Pool@519f3b32 (capacity=1)
		[1] - androidx.sqlite.driver.bundled.BundledSQLiteConnection@dbc2960
		Status: Acquired connection
		Coroutine: [kotlinx.coroutines.UndispatchedMarker@175e4af8, UndispatchedCoroutine{Active}@12e8f431, Dispatchers.IO]
		Acquired:
			at androidx.room.coroutines.ConnectionWithLock.markAcquired(ConnectionPoolImpl.kt:276)
			at androidx.room.coroutines.ConnectionPoolImpl.useConnection(ConnectionPoolImpl.kt:133)
			at androidx.room.coroutines.ConnectionPoolImpl$useConnection$1.invokeSuspend(ConnectionPoolImpl.kt)
			at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
			at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
			at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
			at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
			at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
			at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
			at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
			at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
			at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
			at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
			at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
		
Reader pool:
	androidx.room.coroutines.Pool@164a2e68 (capacity=4)
		[1] - androidx.sqlite.driver.bundled.BundledSQLiteConnection@4ba78529
		Status: Free connection
		[2] - androidx.sqlite.driver.bundled.BundledSQLiteConnection@248cec06
		Status: Free connection
		[3] - androidx.sqlite.driver.bundled.BundledSQLiteConnection@4a20b327
		Status: Free connection
		[4] - androidx.sqlite.driver.bundled.BundledSQLiteConnection@d5efd65
		Status: Free connection

	at androidx.sqlite.SQLite.throwSQLiteException(SQLite.kt:81)
	at androidx.room.coroutines.ConnectionPoolImpl.throwTimeoutException(ConnectionPoolImpl.kt:186)
	at androidx.room.coroutines.ConnectionPoolImpl.useConnection(ConnectionPoolImpl.kt:138)
	at androidx.room.coroutines.ConnectionPoolImpl$useConnection$1.invokeSuspend(ConnectionPoolImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)

**Comment by hua0512** [comment]
Can not reproduce.

**Comment by hua0512** [comment]
[Maybe fixed ](https://issuetracker.google.com/issues/380088809)
